### ISSUE TITLE
some error checking is assumed but not implemented

### ISSUE THREAD

**Issue by esheldon** [LSSTDESC/hpgeom#12]
Here you check for an error
https://github.com/LSSTDESC/hpgeom/blob/859ea11f56822829d9af30ce2090001a10980dd1/hpgeom/hpgeom.c#L254

but no errors are checked for
https://github.com/LSSTDESC/hpgeom/blob/859ea11f56822829d9af30ce2090001a10980dd1/hpgeom/hpgeom_utils.c#L126

**Comment by esheldon** [comment]
I see `hpgeom_check_theta_phi` which could be adapted to work for both degrees and radians

**Comment by erykoff** [comment]
Re: theta/phi and units ... this is the part of the API that I was most uncertain about when I was putting it together.  Following healpy I wanted theta and phi to _only_ be used in radians.  So the `degrees` units is ignored when you have `lonlat=False`.  I thought this would be less confusing than having to specify both `lonlat=False` and `degrees=False` when inputting "traditional" theta/phi values, but I could be convinced the other way around (which would require some minor refactoring and new docstrings).

Re: error checking, that is only called on the outputs from `pix2ang` and suchlike, and not on user input.  But adding an additional check here I think would not hurt.

**Comment by esheldon** [comment]
The code that calls it is checking for an error code on return (hpgeom.c 254), which tells the reader that errors are being checked for.  I think least there should be a comment saying "no errors are actually checked" at the point of call in hpgeom.c to make it clear

**Comment by erykoff** [comment]
Fixed with #14 (at least the error checking).
