### ISSUE TITLE
Does this iterator memory need to be cleaned up?

### ISSUE THREAD

**Issue by esheldon** [LSSTDESC/hpgeom#13]
https://github.com/LSSTDESC/hpgeom/blob/859ea11f56822829d9af30ce2090001a10980dd1/hpgeom/hpgeom.c#L602

**Comment by esheldon** [comment]
I see here that they decref it


https://github.com/numpy/numpy/blob/4d057e633408c04c15292ccc9cd11d96e33a90f5/numpy/core/src/multiarray/arrayobject.c#L827

**Comment by erykoff** [comment]
Fixed with #14.  Thanks!
